Feat/email service setup
Hashtrust-technology-private-limited/django-email-service pull request #2
Opened 2023-05-08 04:56 UTC by Harsh-0196

2023-05-22 08:48 UTC, imlktripathi commented on django_mail_app/email_service/models.py
> +        help_text=_("The last update time, always in Asia/Tokyo timezone."),
why is it in Asia/tokyo timezone? why not utc?

2023-05-22 08:48 UTC, imlktripathi commented on django_mail_app/email_service/models.py
> +    attachment = models.ManyToManyField(Attachment, blank=True)
should be `attachments`

2023-05-22 08:48 UTC, imlktripathi commented on django_mail_app/email_service/models.py
> +    state = models.PositiveSmallIntegerField(
we should call it status

2023-05-22 08:48 UTC, imlktripathi commented on django_mail_app/email_service/tests.py
> +        self.recipients = ['harsh@hashtrust.in']
use dummy email, do not reveal your personal email

2023-06-05 11:39 UTC, VISHU1999 commented on email_service/utils.py
> +        email.status = Email.EmailStatus.error
Should we add error message in remark?

2023-06-05 12:30 UTC, VISHU1999 commented on README.md
> +* subject : subject of email
For every subject we need to create a txt file 
Please add this details in README also

2023-06-05 12:45 UTC, VISHU1999 commented on email_service/templates/users/user_welcome_subject.txt
> +Welcome to Hashtrust
If we can change this flow creating different text file for each subject it would be good 
we can use a JSON file and map template prefix value as a key and map it with subject value and will use this file, instead creating multiple files

2023-06-13 08:49 UTC, Pradhu-MAN requested changes
LOOKS GOOD TO ME FEW MINOR CHANGES AND WE ARE GOOD TO GO.

2023-06-13 08:49 UTC, Pradhu-MAN commented on email_service/utils.py
> +    try:
remove try block use if else statement if we want to do defensive coding technique.

2023-06-13 08:49 UTC, Pradhu-MAN commented on tests/email_service/test_email_service.py
> +
add more test cases for models.py and utils.py

2023-06-15 09:58 UTC, Pradhu-MAN approved these changes

2023-06-15 10:02 UTC, merged